#!/usr/bin/env bash
# One-time setup for the agent-loop runbook.
#
#   scripts/setup.sh [--install-kernel]
#
# Without flags: verifies Rust, Jupyter, and the evcxr kernel are present; writes
# the evcxr user-dependency config that lets notebooks `:dep agent_loop` by name.
#
# With --install-kernel: also builds and registers the evcxr_jupyter kernel
# (requires network; the Rust compile takes a few minutes).
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

say() { printf '\033[1;34m%s\033[0m\n' "$*"; }
die() { printf '\033[1;31m%s\033[0m\n' "$*" >&2; exit 1; }

echo "==> repo: $REPO_DIR"

# 1) Rust
if ! command -v cargo >/dev/null; then die "cargo not found — install Rust via rustup."; fi
echo "==> cargo: $(cargo --version)"

# 2) The crate builds (also caches the build).
(cd "$REPO_DIR" && cargo build --quiet) || die "agent_loop failed to build"
echo "==> agent_loop builds OK"

# 3) Jupyter (either jupyterlab/notebook available, or the venv we set up).
JUP=""
for c in "$REPO_DIR/.venv/bin/jupyter" "$(command -v jupyter || true)"; do
  if [ -n "$c" ] && [ -x "$c" ]; then JUP="$c"; break; fi
done
if [ -z "$JUP" ]; then
  echo "==> jupyter not found. Create a venv and install JupyterLab:"
  echo "      python3 -m venv $REPO_DIR/.venv"
  echo "      $REPO_DIR/.venv/bin/pip install jupyterlab notebook nbformat"
fi
echo "==> jupyter: ${JUP:-<not found — see above>}"

# 4) evcxr kernel.
if [ -x "$HOME/.cargo/bin/evcxr_jupyter" ]; then
  echo "==> evcxr_jupyter present"
else
  if [ "${1:-}" = "--install-kernel" ]; then
    echo "==> installing evcxr_jupyter (this compiles for a few minutes)..."
    cargo +stable install evcxr_jupyter --locked
    "$HOME/.cargo/bin/evcxr_jupyter" --install
  else
    echo "==> evcxr_jupyter missing. Re-run with --install-kernel to install it."
  fi
fi

# 5) Write the evcxr user-dependency config so notebooks can `:dep agent_loop`.
CFG="$HOME/.config/evcxr/evcxr_user_deps.toml"
mkdir -p "$(dirname "$CFG")"
cat > "$CFG" <<EOF
# Autogenerated by $0. Registers the local agent-loop crate for evcxr.
[user_dependencies]
agent_loop = { path = "$REPO_DIR" }
EOF
echo "==> wrote $CFG"

echo
say "Setup complete. To run the presentation (uses your live model):"
echo "   1. Configure the endpoint (either way works):"
echo "      cp $REPO_DIR/.env.example $REPO_DIR/.env && vim $REPO_DIR/.env"
echo "      # set it to your real endpoint/model, e.g."
echo "      #   OPENAI_BASE_URL=https://api.openai.com/v1   or your LLM gateway"
echo "      #   OPENAI_API_KEY=sk-..."
echo "      #   AGENT_LOOP_MODEL=gpt-4o-mini"
echo "   2. Launch Jupyter (this reads .env automatically):"
echo "      $JUP lab --notebook-dir notebooks"
echo "   3. Open 00_welcome.ipynb and run top-to-bottom against your model."
echo
say "To (re)generate executed outputs against your configured model:"
echo "   $REPO_DIR/scripts/execute_notebooks.sh"
